const mockGenderList = {
    results: [
        {
          list_name: "hardcover-fiction",
          display_name: "Ficção de Capa Dura",
          list_name_encoded: "hardcover-fiction",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-nonfiction",
          display_name: "Não Ficção de Capa Dura",
          list_name_encoded: "hardcover-nonfiction",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "combined-print-and-e-fiction",
          display_name: "Ficção Impressa e Eletrônica Combinada",
          list_name_encoded: "combined-print-and-e-fiction",
          oldest_published_date: "2011-02-13",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "combined-print-and-e-nonfiction",
          display_name: "Não Ficção Impressa e Eletrônica Combinada",
          list_name_encoded: "combined-print-and-e-nonfiction",
          oldest_published_date: "2011-02-13",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "trade-fiction-paperback",
          display_name: "Livro de Bolso de Ficção",
          list_name_encoded: "trade-fiction-paperback",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "mass-market-paperback",
          display_name: "Livro de Bolso de Mercado de Massa",
          list_name_encoded: "mass-market-paperback",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-10-22",
          updated: "2023-10-22 12:00:00",
        },
        {
          list_name: "paperback-nonfiction",
          display_name: "Não Ficção de Livro de Bolso",
          list_name_encoded: "paperback-nonfiction",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "advice-how-to-and-miscellaneous",
          display_name: "Conselhos, Como Fazer e Diversos",
          list_name_encoded: "advice-how-to-and-miscellaneous",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "childrens-middle-grade-hardcover",
          display_name: "Capa Dura Infantil de Grau Médio",
          list_name_encoded: "childrens-middle-grade-hardcover",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "childrens-picture-books",
          display_name: "Livros Ilustrados Infantis",
          list_name_encoded: "childrens-picture-books",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "childrens-series",
          display_name: "Séries Infantis",
          list_name_encoded: "childrens-series",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "young-adult-hardcover",
          display_name: "Capa Dura para Jovens Adultos",
          list_name_encoded: "young-adult-hardcover",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "young-adult-paperback",
          display_name: "Livro de Bolso para Jovens Adultos",
          list_name_encoded: "young-adult-paperback",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "e-book-fiction",
          display_name: "Ficção de E-book",
          list_name_encoded: "e-book-fiction",
          oldest_published_date: "2011-02-13",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "e-book-nonfiction",
          display_name: "Não Ficção de E-book",
          list_name_encoded: "e-book-nonfiction",
          oldest_published_date: "2011-02-13",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-graphic-books",
          display_name: "Livros Gráficos de Capa Dura",
          list_name_encoded: "hardcover-graphic-books",
          oldest_published_date: "2009-07-12",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-graphic-books",
          display_name: "Livros Gráficos de Livro de Bolso",
          list_name_encoded: "paperback-graphic-books",
          oldest_published_date: "2019-06-09",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "manga",
          display_name: "Mangá",
          list_name_encoded: "manga",
          oldest_published_date: "2019-06-09",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "business-books",
          display_name: "Livros de Negócios",
          list_name_encoded: "business-books",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "food-and-fitness",
          display_name: "Alimentos e Boa Forma",
          list_name_encoded: "food-and-fitness",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "travel",
          display_name: "Viagem",
          list_name_encoded: "travel",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "science",
          display_name: "Ciência",
          list_name_encoded: "science",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "sports",
          display_name: "Esportes",
          list_name_encoded: "sports",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "humor",
          display_name: "Humor",
          list_name_encoded: "humor",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "poetry",
          display_name: "Poesia",
          list_name_encoded: "poetry",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "arts-and-leisure",
          display_name: "Artes e Lazer",
          list_name_encoded: "arts-and-leisure",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "religion-spirituality-and-faith",
          display_name: "Religião, Espiritualidade e Fé",
          list_name_encoded: "religion-spirituality-and-faith",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "audio-fiction",
          display_name: "Ficção em Áudio",
          list_name_encoded: "audio-fiction",
          oldest_published_date: "2018-03-18",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "audio-nonfiction",
          display_name: "Não Ficção em Áudio",
          list_name_encoded: "audio-nonfiction",
          oldest_published_date: "2018-03-18",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "graphic-books-and-manga",
          display_name: "Livros Gráficos e Mangá",
          list_name_encoded: "graphic-books-and-manga",
          oldest_published_date: "2019-06-09",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "mass-market-monthly",
          display_name: "Mercado de Massa Mensal",
          list_name_encoded: "mass-market-monthly",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-10-22",
          updated: "2023-10-22 12:00:00",
        },
        {
          list_name: "picture-books",
          display_name: "Livros Ilustrados",
          list_name_encoded: "picture-books",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "series-books",
          display_name: "Livros de Série",
          list_name_encoded: "series-books",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "young-adult",
          display_name: "Jovem Adulto",
          list_name_encoded: "young-adult",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-political-books",
          display_name: "Livros Políticos de Capa Dura",
          list_name_encoded: "hardcover-political-books",
          oldest_published_date: "2020-03-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "picture-book",
          display_name: "Livro Ilustrado",
          list_name_encoded: "picture-book",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "series-book",
          display_name: "Livro de Série",
          list_name_encoded: "series-book",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "middle-grade-hardcover",
          display_name: "Capa Dura de Grau Médio",
          list_name_encoded: "middle-grade-hardcover",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-advice",
          display_name: "Conselhos de Capa Dura",
          list_name_encoded: "hardcover-advice",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-business",
          display_name: "Negócios de Capa Dura",
          list_name_encoded: "hardcover-business",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-cookbooks",
          display_name: "Livros de Culinária de Capa Dura",
          list_name_encoded: "hardcover-cookbooks",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-health",
          display_name: "Saúde de Capa Dura",
          list_name_encoded: "hardcover-health",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-sports",
          display_name: "Esportes de Capa Dura",
          list_name_encoded: "hardcover-sports",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-travel",
          display_name: "Viagem de Capa Dura",
          list_name_encoded: "hardcover-travel",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-science",
          display_name: "Ciência de Capa Dura",
          list_name_encoded: "hardcover-science",
          oldest_published_date: "2012-08-01",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-humor",
          display_name: "Humor de Capa Dura",
          list_name_encoded: "hardcover-humor",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-poetry",
          display_name: "Poesia de Capa Dura",
          list_name_encoded: "hardcover-poetry",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-arts",
          display_name: "Artes de Capa Dura",
          list_name_encoded: "hardcover-arts",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-religion",
          display_name: "Religião de Capa Dura",
          list_name_encoded: "hardcover-religion",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "hardcover-audio",
          display_name: "Áudio de Capa Dura",
          list_name_encoded: "hardcover-audio",
          oldest_published_date: "2018-03-18",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-advice",
          display_name: "Conselhos de Livro de Bolso",
          list_name_encoded: "paperback-advice",
          oldest_published_date: "2008-06-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-business",
          display_name: "Negócios de Livro de Bolso",
          list_name_encoded: "paperback-business",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-cookbooks",
          display_name: "Livros de Culinária de Livro de Bolso",
          list_name_encoded: "paperback-cookbooks",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-health",
          display_name: "Saúde de Livro de Bolso",
          list_name_encoded: "paperback-health",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-sports",
          display_name: "Esportes de Livro de Bolso",
          list_name_encoded: "paperback-sports",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-travel",
          display_name: "Viagem de Livro de Bolso",
          list_name_encoded: "paperback-travel",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-science",
          display_name: "Ciência de Livro de Bolso",
          list_name_encoded: "paperback-science",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-humor",
          display_name: "Humor de Livro de Bolso",
          list_name_encoded: "paperback-humor",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-poetry",
          display_name: "Poesia de Livro de Bolso",
          list_name_encoded: "paperback-poetry",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-arts",
          display_name: "Artes de Livro de Bolso",
          list_name_encoded: "paperback-arts",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-religion",
          display_name: "Religião de Livro de Bolso",
          list_name_encoded: "paperback-religion",
          oldest_published_date: "2012-01-08",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
        {
          list_name: "paperback-audio",
          display_name: "Áudio de Livro de Bolso",
          list_name_encoded: "paperback-audio",
          oldest_published_date: "2018-03-18",
          newest_published_date: "2023-11-26",
          updated: "2023-11-26 12:00:00",
        },
      ]
}  

  
  export default mockGenderList;